#GAME THAT TAKES PLAYER THROUGH MAZE
#IF YOU ANSWER RIGHT, YOU PROCEED
#IF YOU ANSWER WRONG FIRST TIME, YOU LOSE POINTS
#IF YOU ANSWER WRONG AGAIN, YOU DIE
#IN THE END YOU GET TO WRITE YOUR BIOGRAPHY 